import type { Metadata } from 'next'
import "./globals.css"
import { robotoMedium } from '@/app/components/ui/fonts/roboto-fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotoMedium.className}>
        {children}
      </body>
    </html>
  )
}